import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import { cookies } from "next/headers";
import { Suspense } from "react";
import { GlobalFeedbackForm } from "@/components/GlobalFeedbackForm";
import { GlobalPartnersSection } from "@/components/GlobalPartnersSection";
import { PreventHorizontalPageScroll } from "@/components/PreventHorizontalPageScroll";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteNavbar } from "@/components/SiteNavbar";
import { SiteMainColumn } from "@/components/SiteMainColumn";
import { ScrollToTop } from "@/components/ScrollToTop";
import { ViewportHeightSync } from "@/components/ViewportHeightSync";
import { NAV_FOLDERS_COOKIE_NAME, parseNavFoldersCookie } from "@/lib/navFoldersCookie";
import { apiBaseUrl } from "@/lib/apiBaseUrl";
import "./globals.css";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico?v=logo", sizes: "any" },
      { url: "/favicon.png?v=logo", type: "image/png" },
    ],
  },
};

type SiteSettings = {
  email: string;
  phone: string;
  address: string;
  social: {
    vk: string;
    telegram: string;
    max: string;
    whatsapp: string;
  };
  requisites: {
    companyName: string;
    inn: string;
    kpp: string;
    ogrn: string;
  };
  documents?: {
    name: string;
    size: number;
    dataUrl: string;
  }[];
  topRibbonMessages?: string[];
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialFolderNavItems = parseNavFoldersCookie(
    cookieStore.get(NAV_FOLDERS_COOKIE_NAME)?.value,
  );

  let siteSettings: SiteSettings | null = null;
  const base = apiBaseUrl();
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10_000);
    const res = await fetch(`${base}/api/pages/site-settings`, {
      cache: "no-store",
      signal: controller.signal,
    }).finally(() => clearTimeout(timeoutId));
    if (res.ok) {
      const data = (await res.json()) as { settings?: SiteSettings };
      if (data?.settings) siteSettings = data.settings;
    }
  } catch {
    siteSettings = null;
  }

  return (
    <html lang="en">
      <body
        className={`${exo2.className} flex min-h-screen flex-col antialiased`}
        style={{ backgroundColor: "#f3f4f6", color: "#020617" }}
      >
        <PreventHorizontalPageScroll />
        <Suspense fallback={null}>
          <ScrollToTop />
        </Suspense>
        <ViewportHeightSync />
        <SiteNavbar initialFolderNavItems={initialFolderNavItems} siteSettings={siteSettings} />
        {/* overflow-x-hidden здесь, не на body — иначе sticky-шапка не прилипает к viewport (clip в старых WebKit давал артефакты). */}
        <SiteMainColumn>
          <div className="flex w-full min-h-0 flex-col">{children}</div>
          <GlobalFeedbackForm />
          <GlobalPartnersSection />
          <SiteFooter siteSettings={siteSettings} />
        </SiteMainColumn>
      </body>
    </html>
  );
}
