import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { GlobalFeedbackForm } from "@/components/GlobalFeedbackForm";
import { PreventHorizontalPageScroll } from "@/components/PreventHorizontalPageScroll";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteNavbar } from "@/components/SiteNavbar";
import { NAV_FOLDERS_COOKIE_NAME, parseNavFoldersCookie } from "@/lib/navFoldersCookie";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type SiteSettings = {
  email: string;
  phone: string;
  address: string;
  social: {
    vk: string;
    telegram: string;
    max: string;
    whatsapp: string;
  };
  requisites: {
    companyName: string;
    inn: string;
    kpp: string;
    ogrn: string;
  };
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialFolderNavItems = parseNavFoldersCookie(
    cookieStore.get(NAV_FOLDERS_COOKIE_NAME)?.value,
  );

  let siteSettings: SiteSettings | null = null;
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 1500);
    const res = await fetch(`${apiUrl}/api/pages/site-settings`, {
      cache: "no-store",
      signal: controller.signal,
    }).finally(() => clearTimeout(timeoutId));
    if (res.ok) {
      const data = (await res.json()) as { settings?: SiteSettings };
      if (data?.settings) siteSettings = data.settings;
    }
  } catch {
    siteSettings = null;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
        style={{ backgroundColor: "#f3f4f6", color: "#020617" }}
      >
        <PreventHorizontalPageScroll />
        <SiteNavbar initialFolderNavItems={initialFolderNavItems} siteSettings={siteSettings} />
        <div className="flex min-h-0 flex-1 flex-col">{children}</div>
        <GlobalFeedbackForm />
        <SiteFooter siteSettings={siteSettings} />
      </body>
    </html>
  );
}
